name: Get Flag

on: [workflow_dispatch]

permissions:
  id-token: write   # CRÍTICO — sin esto no funciona el OIDC
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: 808bc472-30e6-4e41-8d22-7881db11aa09
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: 5ff86dd0-ee91-4f26-901a-158f9242c514
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage blob download \
            --account-name <STORAGE_NAME> \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login

      - name: Read flag
        run: cat flag.txt
