name: Get Flag

on: [workflow_dispatch]

permissions:
  id-token: write   # CRÍTICO — sin esto no funciona el OIDC
  contents: read

jobs:
  get-flag:
    runs-on: ubuntu-latest
    steps:

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: <MANAGED_IDENTITY_CLIENT_ID>
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: <SUBSCRIPTION_ID>
          enable-AzPSSession: true

      - name: Download flag
        run: |
          az storage blob download \
            --account-name <STORAGE_NAME> \
            --container-name flag \
            --name flag.txt \
            --file flag.txt \
            --auth-mode login

      - name: Read flag
        run: cat flag.txt
